## Settings Configuration

# World Spawn Location
world:
  spawn-location:
    world: world         # World name (default: 'world')
    x: 0                 # X coordinate of the spawn location
    y: 0                # Y coordinate of the spawn location
    z: 0                 # Z coordinate of the spawn location
    yaw: 0               # Yaw (rotation) at spawn location
    pitch: 0             # Pitch (vertical angle) at spawn location
  set-auto-spawnlocation: false # Automatically set spawn location
  do-daylight-cycle: false # Automatically sets game rules for DO_DAYLIGHT_CYCLE
  do-weather-cycle: false # Automatically sets game rules for DO_WEATHER_CYCLE
  world-time: 18000 # Automatically sets the time in the world
  clear-weather: true # Automatically clears weather to avoid rain, thunder, etc.

# Server Settings
server:
  motd: "&dHello &cWorld"
  max-players: 50        # Maximum number of players allowed on the server (default: 50)

# Plugin Settings
plugin:
  enable-logging: true
  check-for-updates: true