name: LobbySystem
version: '1.0.1-Beta'
main: com.tnecnivvv.lobbySystem.LobbySystem
api-version: '1.21'
authors: [tnecnivvv]
description: Lightweight LobbySystem
permissions:
  lobbysystem.update.notification:
    description: Allows players to receive update notifications.
    default: op